apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 0  # BAD: Running as root
          privileged: true  # BAD: Privileged container
        env:
        - name: API_KEY
          value: "sk-1234567890abcdef"  # BAD: Hardcoded secret
        resources: {}  # BAD: No resource limits
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web-app
